name: "Pull Request Labeler"
on: [pull_request_target]

permissions:
  pull-requests: write

jobs:
  triage:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
